CREATE TABLE "HR"."DBUSER" 
   (	"USER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("USER_ID"));
