package jrout.tutorial.hibernate.model;

// Generated Mar 15, 2015 6:09:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomerId generated by hbm2java
 */
@Embeddable
public class CustomerId implements java.io.Serializable {

	private int cid;
	private int tid;

	public CustomerId() {
	}

	public CustomerId(int cid, int tid) {
		this.cid = cid;
		this.tid = tid;
	}

	@Column(name = "CID", nullable = false, precision = 5, scale = 0)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	@Column(name = "TID", nullable = false, precision = 5, scale = 0)
	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CustomerId))
			return false;
		CustomerId castOther = (CustomerId) other;

		return (this.getCid() == castOther.getCid())
				&& (this.getTid() == castOther.getTid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCid();
		result = 37 * result + this.getTid();
		return result;
	}

}
