//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 09:24:30 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tutorial.jayramrout/employee/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jayramrout.tutorial.employee.schemas;
