
package com.tutorial.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderProcess", targetNamespace = "http://ws.tutorial.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderProcess {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processOrder", targetNamespace = "http://ws.tutorial.com/", className = "com.tutorial.ws.ProcessOrder")
    @ResponseWrapper(localName = "processOrderResponse", targetNamespace = "http://ws.tutorial.com/", className = "com.tutorial.ws.ProcessOrderResponse")
    public String processOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

}
