package com.tutorial.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-23T14:12:35.189-05:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://ws.tutorial.com/", name = "OrderProcess")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderProcess {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processOrder", targetNamespace = "http://ws.tutorial.com/", className = "com.tutorial.ws.ProcessOrder")
    @WebMethod
    @ResponseWrapper(localName = "processOrderResponse", targetNamespace = "http://ws.tutorial.com/", className = "com.tutorial.ws.ProcessOrderResponse")
    public java.lang.String processOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        com.tutorial.ws.Order arg0
    );
}
