
package com.tutorial.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderProcessImplService", targetNamespace = "http://ws.tutorial.com/", wsdlLocation = "http://localhost:8081/WSSecureUsernamePassword_Web/OrderProcess?wsdl")
public class OrderProcessImplService
    extends Service
{

    private final static URL ORDERPROCESSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERPROCESSIMPLSERVICE_EXCEPTION;
    private final static QName ORDERPROCESSIMPLSERVICE_QNAME = new QName("http://ws.tutorial.com/", "OrderProcessImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/WSSecureUsernamePassword_Web/OrderProcess?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERPROCESSIMPLSERVICE_WSDL_LOCATION = url;
        ORDERPROCESSIMPLSERVICE_EXCEPTION = e;
    }

    public OrderProcessImplService() {
        super(__getWsdlLocation(), ORDERPROCESSIMPLSERVICE_QNAME);
    }

    

    public OrderProcessImplService(URL wsdlLocation) {
        super(wsdlLocation, ORDERPROCESSIMPLSERVICE_QNAME);
    }

    

    public OrderProcessImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns OrderProcess
     */
    @WebEndpoint(name = "OrderProcessImplPort")
    public OrderProcess getOrderProcessImplPort() {
        return super.getPort(new QName("http://ws.tutorial.com/", "OrderProcessImplPort"), OrderProcess.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderProcess
     */
    @WebEndpoint(name = "OrderProcessImplPort")
    public OrderProcess getOrderProcessImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.tutorial.com/", "OrderProcessImplPort"), OrderProcess.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERPROCESSIMPLSERVICE_EXCEPTION!= null) {
            throw ORDERPROCESSIMPLSERVICE_EXCEPTION;
        }
        return ORDERPROCESSIMPLSERVICE_WSDL_LOCATION;
    }

}
